### ISSUE TITLE
AppData: don't repeat summary in description

### ISSUE THREAD

**Issue by cassidyjames** [manexim/news#4]
Not a hard failure, but just a heads up that this is gonna look bad :smile: 

https://github.com/manexim/news/blob/5c7d90fa1819e24e13427473aac639e876dfa9bf/data/com.github.manexim.news.appdata.xml#L8-L11

You can test by running:

```shell
io.elementary.appcenter -l data/com.github.manexim.news.appdata.xml
```

![Screenshot from 2019-11-06 12 35 30@2x](https://user-images.githubusercontent.com/611168/68331337-11147500-0092-11ea-942a-9449f3f2a0a8.png)

**Comment by meisenzahl** [comment]
Thanks for the hint.

I'm afraid the test with `io.elementary.appcenter -l data/com.github.manexim.news.appdata.xml` doesn't work for me. AppCenter starts as usual without the parameter.

**Comment by cassidyjames** [comment]
@meisenzahl you may need to `killall io.elementary.appcenter` first if it's already running, and make sure you're pointing it to the actual path of your AppData.

**Comment by meisenzahl** [comment]
If I quit AppCenter before with the command, it works. Many thanks for the help!
