### ISSUE TITLE
Add in-app loading view

### ISSUE THREAD

**Issue by NathanBnm** [manexim/news#7]
It would be great to display a loading view while retrieving info because at the moment the app is not showing immediately because it has to fetch the news first (specifically for slow connections).

Users may wonder why the application does not open right away, adding a loading view would be less frustrating.

**Comment by meisenzahl** [comment]
@NathanBnm My plan is that the articles are loaded in the background and then added one by one. During testing, however, crashes occurred from time to time.

A loading screen is a good alternative until then.

**Comment by meisenzahl** [comment]
@NathanBnm The articles are now loaded in the background and a loading screen is displayed. Please give it a try :)

**Comment by NathanBnm** [comment]
I'll try that

**Comment by NathanBnm** [comment]
@meisenzahl it's working well :smile:

When clicking an article, you should remove the "News Feed" | "Sources" tabs and put the title instead as it was before don't you think?
