### ISSUE TITLE
Issue with app name in headerbar

### ISSUE THREAD

**Issue by NathanBnm** [manexim/news#9]
When launching the app, the header bar displays the app name, but when clicking on a news and going back, it's back to the RDNN.

On launch:

![image](https://user-images.githubusercontent.com/45366162/68542984-f0aa2a80-03b1-11ea-90a4-0926f472c030.png)

After going back:

![image](https://user-images.githubusercontent.com/45366162/68543003-0881ae80-03b2-11ea-8c58-371d4be8a487.png)

**Comment by meisenzahl** [comment]
Thanks for reporting. I already fixed it with https://github.com/manexim/news/commit/a72001122c972326a5fa998e1ae999e0a9e2397e

**Comment by NathanBnm** [comment]
Oh I didn't see that. Great!
